ALTER TABLE `oxorder` ADD `FCIDEALO_ORDERNR` VARCHAR( 32 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `oxorder` ADD `FCIDEALO_DELIVERY_CARRIER` VARCHAR( 32 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `oxorder` ADD `FCIDEALO_ORDERNR_SENT` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `oxorder` ADD `FCIDEALO_FULFILLMENT_SENT` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `oxorder` ADD `FCIDEALO_TRACKINGCODE_SENT` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `oxorder` ADD `FCIDEALO_REVOCATION_SENT` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';